# Generated by Django 4.0.3 on 2022-03-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=125, verbose_name='Nome da Instituicao de ensino')),
                ('nome_curso', models.CharField(max_length=125, verbose_name='Nome do curso')),
            ],
            options={
                'db_table': 'instituicao',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125, verbose_name='Nome Completo')),
                ('id_instituicao', models.ForeignKey(db_column='id_instituicao', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz_app.instituicao')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('id_instituicao', models.ForeignKey(db_column='id_instituicao', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz_app.instituicao')),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='CadastrodePerguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, verbose_name='Digite sua pergunta')),
                ('resposta_alternativa', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Resposta')),
                ('resposta_extenso', models.CharField(max_length=100, verbose_name='Digite a resposta')),
                ('explicacao', models.TextField(blank=True, null=True, verbose_name='Digite a explicação do livro/apostila da resposta')),
                ('grau_de_dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1, verbose_name='Grau de dificuldade')),
                ('id_disciplina', models.ForeignKey(blank=True, db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz_app.disciplina')),
                ('id_professor', models.ForeignKey(blank=True, db_column='id_professor', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz_app.professor')),
            ],
            options={
                'db_table': 'cadastro_perguntas',
            },
        ),
    ]
